### PR TITLE
Operator state

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by mathturtle** [comment]
I found a crash...

* Load a dataset, apply some operators (include a Set Tilt Angles)
* Use the C++ reconstruction operator
* Save state, reset, load state
* Quickly cancel the reconstruction while it is running (not sure this is necessary, but I'm impatient)
* Delete the reconstruction operator (the crash is in a lambda in DataSource::deserialize that I think needs a better signal connection lifetime)

**Comment by mathturtle** [comment]
And another:

* Load a dataset apply some operators
* Snapshot the data
* Save data for the snapshotted data (not sure this is necessary)
* Save state, reset, load state... crash.  Looks like the modules on the output are messed up?

**Comment by cryos** [comment]
I don't think either of these issues is the result of this branch, I have created issues #1486 and #1487 to track them.

**Comment by mathturtle** [comment]
Sounds good.  i didn't test master to see if these were reproducible there.

**Comment by cryos** [comment]
I am still tracking down a few issues like that, some big changes

**Pull request merged**
