### PR TITLE
  Refactor itk python

### PR DESCRIPTION
**Pull request by cquammen**

### CODE REVIEW

**Comment by cquammen** [comment]
@cjh1 PTAL

**Comment by cjh1** [comment]
@cquammen LGTM, one thought/suggest. What about making utils a package, then we could have a itk module called utils.itk? And general utils in utils/_init__.py? We could eventually separate out utils further and have a utils.vtk ...

**Comment by cquammen** [comment]
That sounds reasonable to me, but I defer to @cryos .

**Comment by cquammen** [comment]
@cryos Please weigh in.

**Pull request merged**
