### PR TITLE
Delay valueChanged events to improve UI responsiveness when typing

### PR DESCRIPTION
**Pull request by mathturtle**
valueChanged fires after every character typed and for slower operations
this can be annoying.  But editingFinished doesn't fire when the up/down
arrows are clicked on spin boxes, which is also annoying.

For #479.  @cryos @Hovden I don't know if I like this any better.  It fixes the typing issue but breaks the live update when clicking the arrows on the spin box (at least on Linux).

### CODE REVIEW

**Comment by cryos** [comment]
Isn't there another signal for when the arrows are clicked?

**Comment by cryos** [comment]
Yeah I guess not, we could get a little clever and fire a one shot timer, only update after 1 second or something. I would have hoped editingFinished would have been emitted after the arrows have been clicked.

**Comment by mathturtle** [comment]
Here is the update with the one-shot timer.  1 second seems too long in some cases, but I think we should err on the long side for now.

**Comment by cquammen** [comment]
Boy, this is a lot of code. I worry about maintaining it. Something more encapsulated, like a custom Qt spin box that fires the signals you want, would probably be preferable.

**Comment by mathturtle** [comment]
You have a point Cory.  And I'm not really happy with the solution...  I'm working on a new version that detects clicks to the buttons in the spin box (based on [this thread](https://forum.qt.io/topic/61529/about-qspinbox-how-to-make-it-emit-editingfinished-signal-when-click-the-up-down-arrow-button/7)).  I have no idea why Qt doesn't provide a signal for this.

**Comment by mathturtle** [comment]
Here is a new version that uses a custom subclass of QSpinBox/QDoubleSpinBox that makes the editing finished signal behave the way we want it to.

**Comment by Hovden** [comment]
I suggest 250 milliseconds. According to Google, this is the magic number for people's patience regarding delays in UI (http://www.nytimes.com/2012/03/01/technology/impatient-web-users-flee-slow-loading-sites.html)

**Comment by cryos** [comment]
So my main suggestion would be to shorten the class names, they are already in the tomviz namespace, and the Qt ones are called QSpinBox. Why not go with tomviz::SpinBox and tomviz::DoubleSpinBox? Otherwise looks great, and glad we can forego the arbitrary delay. Good to know the magic number should we need to use arbitrary delays in other places though, I will try to remember that.

**Comment by mathturtle** [comment]
Updated with shortened class names.  My one concern is will `#include "SpinBox.h"` be ambiguous?  Hopefully CMake puts that include directory first.

**Comment by cquammen** [comment]
I don't think there is another header file named `SpinBox.h` included in tomviz. Qt's header is QSpinBox, QDoubleSpinBox, etc.

Tested locally, works great.

LGTM

**Comment by cryos** [comment]
I am not worried about name collision, and "" around includes means take the local file first anyway.

**Pull request merged**
