### PR TITLE
First pass at a command line pipeline runner

### PR DESCRIPTION
**Pull request by cjh1**
Supposes a simple operator pipeline using a EMD data source.

screenshot from 2018-04-04 14-17-57

### CODE REVIEW

**Comment by cjh1** [comment]
@mathturtle I have pushed a commit that gives a better message if you try a C++ operator.

**Comment by cryos** [comment]
You have made some travis stuff angry, this is looking great, and I spoke about it with several people at NCEM yesterday. We should figure out how to keep travis happy before merging.

**Comment by cjh1** [comment]
@cryos I will fix the issues, I have a couple more commits coming to a test for this functionality.

**Comment by cjh1** [comment]
@cryos I have soothed the savage beast that is Travis! Can I get a green mark on this?

**Pull request merged**
