### PR TITLE
Label object distance from axis

### PR DESCRIPTION
**Pull request by cquammen**
Added Label Object Distance From Principal Axes operator

Computes the distance from the centroid of each connected component in a label object with the given label_value to the given principal axis and store that distance in each voxel of the label object connected component. A principal_axis of 0 is first principal axis, 1 is the second, and 2 is third.

### CODE REVIEW

**Comment by cjh1** [comment]
@cquammen Code looks good can you give me the recipe to test?

**Comment by cquammen** [comment]
Sure, sorry for leaving that out.

* Load SMALL_PtCu_NanoParticle
* Data Transforms -> Binary Threshold, default parameters
* Click on Thresholded Segmentation child dataset. Data Transforms -> Label Object Principal Axes, default arguments
* Data Transforms -> Label Object Distance from Principal Axes, default arguments
* Add Volume module to the Thresholded Segmentation child dataset.
* Add a Contour module to the SMALL_PtCu_NanoParticle, Select Color checked to white, set Opacity to 0.04.

You should see the following:

image

The first principal axis of the object runs left to right in the image. Small connected components close to this axis have colors from the low end of the color map. The largest connected component centroid is very close to the centroid of the entire object, so its distance is near zero, hence it maps to the background color, i.e., is not visible.

**Comment by cjh1** [comment]
@cquammen Thanks for the instructions, I am not seeing a progress dialog for 'Label Object Principal Axes' any idea why or is that by design?

**Comment by cquammen** [comment]
For some reason the progress dialog does not show when operators are applied to child datasets (#648).

**Pull request merged**
