### PR TITLE
Added 3D Sobel Filter

### PR DESCRIPTION
**Pull request by yijiang1**
Changed the "sobel filter" in Data Transforms menu to 3D instead of 1D.
This addresses case 1 in #299 .

### CODE REVIEW

**Comment by Hovden** [comment]
Does the gradient magnitude use the same laplace kernel? If not, do we need to change the name from "Sobel" to "Gradient Magnitude"?

We can merge this if it's ready.

**Comment by yijiang1** [comment]
> Does the gradient magnitude use the same laplace kernel?

Laplace operator (filter) approximates the second derivative of the image.
Sobel operator (filter) approximates the first derivative. 

For edge detection, we often do two things:
1. Calculate the gradient image, which depends on the operator we use.
2. Calculate the magnitude of the gradient image.

**Comment by Hovden** [comment]
My question, pertained more to the algorithm being used. But looking more closely I see that the function takes in an argument that specifies that it will calculated using the sobel filter:

scipy.ndimage.filters.generic_gradient_magnitude(array, scipy.ndimage.filters.sobel)

But I'm still confused as to what the axial direction of the sobel kernel is and how the user selects it.

**Comment by yijiang1** [comment]
It first approximates the gradients along all three directions (say, Gx, Gy, Gz) using Sobel operator and then calculates the magnitude of the gradient image (sqrt(Gx^2+Gy^2+Gz^2)). Thus the user doesn't need to select anything.

In the old version it basically calculates Gx, Gy, or Gz, which can be specified by the user.

Based on #299 , I thought we want the gradient magnitude image instead of a gradient along a particular direction.

**Comment by ercius** [comment]
I think the new 3D function accomplishes what most users would want. I.e.
along all directions simultaneously.

**Comment by yijiang1** [comment]
@Hovden Can we merge this now?

**Comment by Hovden** [comment]
I'm still confused why it is being called a Sobel filter when it using the gradient magnitude.

**Comment by yijiang1** [comment]
So we call it "Gradient Magnitude using Sobel Filter"?

**Comment by Hovden** [comment]
We could call it "Gradient Magnitude" and then in the Python file, add a comment explaining how it is calculated.

**Comment by yijiang1** [comment]
OK.

**Comment by yijiang1** [comment]
I changed "sobel filters" to "gradient magnitude" and added descriptions in python code.

**Pull request merged**
