### PR TITLE
Switch from JsonCPP to QJson API

### PR DESCRIPTION
**Pull request by cquammen**

### CODE REVIEW

**Comment by cquammen** [comment]
@cryos Addresses #664.

**Comment by cquammen** [comment]
Ready for review.

**Comment by cjh1** [comment]
Looks like two references escaped the conversion:

```
tomviz/AlignWidget.cxx:834:  connect(&dialog, SIGNAL(applyPreset(const Json::Value&)),
tomviz/HistogramWidget.cxx:261:  connect(&dialog, SIGNAL(applyPreset(const Json::Value&)),
 ```

Everything complied and seems to run OK, but I probably didn't exercise these code paths.

**Comment by cquammen** [comment]
The signal `applyPreset(const Json::Value&)` belongs to `pqPresetDialog`, a ParaView class, so we can't change these.

**Pull request merged**
