### PR TITLE
Add a python transform to clear a part of the volume

### PR DESCRIPTION
**Pull request by mathturtle**
This transform replaces a volume of interest with zeros.  This is my solution to #199 .  The code for the non-modal dialog probably isn't ideal for non-programmers to copy and reuse.

### CODE REVIEW

**Comment by yijiang1** [comment]
Works well. Tested OSX.
One minor thing: the UI still say "**Crop** data start/end".

**Comment by mathturtle** [comment]
Good catch @yijiang1.  I've put up a new version that changes it to 'Volume Selected start/end' for both crop and this operation.

**Comment by mathturtle** [comment]
Rebased to avoid conflicts.

**Comment by Hovden** [comment]
Merge?

**Comment by Hovden** [comment]
Merging so it can be used by colleagues (non-programmers).

**Pull request merged**
