### PR TITLE
Update itk build

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by cryos** [comment]
We should choose a release or SHA for default checkout, need to determine if we can exclude rgba (leads to a configure error in master).

**Comment by cryos** [comment]
Just taking a second look at this now, looking at targeting what works in ITK 4.11.

**Comment by cryos** [comment]
Just building now, I backed off on removing the rgb/rgba types (I think we can live with them, and would rather use a release tag). Any thoughts, opinions? These would feed into updating our superbuild if they look reasonable.

**Comment by cryos** [comment]
Thanks @cquammen, that is all I wanted. This is just the new recommendation I came up with when talking to @thewtex last week. I will merge this for now, but we can certainly revisit if issues arise.

**Comment by thewtex** [comment]
+1 LGTM

**Pull request merged**
