### PR TITLE
Perona-Malik anisotropic diffusion

### PR DESCRIPTION
**Pull request by cquammen**
This change exposes ITK's Perona-Malik gradient-based anisotropic diffusion filter.

Addresses enhancement request #475.

### CODE REVIEW

**Comment by Hovden** [comment]
@floridian0105 will be happy.

**Comment by Hovden** [comment]
Code looks OK to me.

**Comment by yijiang1** [comment]
I get this error on my local build:
Exception encountered while runningPeronaMalikAnisotropicDiffusion
"itkTemplate : No template (<class 'itkImagePython.itkImageUC3'>, <class 'itkImagePython.itkImageUC3'>) for the itk::GradientAnisotropicDiffusionImageFilter class"

**Comment by cquammen** [comment]
Ah, sorry, I should have included testing instructions.

* Load data set
* Run `Convert to Float`
* Run Perona-Malik Anisotropic Diffusion`

The error you see is because the ITK Python wrapping does not wrap integral voxel type images, hence there is no filter that can handle the integral types that Tomviz often deals with. A workaround for now is the `Convert to Float` transform to the data set.

Soon, I will submit a pull request with modifications to transforms like this that will do the conversion under the hood.

**Comment by floridian0105** [comment]
Thanks much!

**Pull request merged**
