### PR TITLE
Added a function that bin tilt series by 2

### PR DESCRIPTION
**Pull request by yijiang1**
Added a python function that bin tilt series by 2 to tomography menu. This addresses #539 

I also renamed to the old "Downsample x2" function in data transform menu to "Bin volume x2" and added a feature to downsample tilt angles in case the dataset is marked as a tilt series.

### CODE REVIEW

**Comment by mathturtle** [comment]
The changes make sense.  My main concern is the text for the menu items.  Will people in your field know what 'Bin Volume x2' means?  I know they understand 'Downsample x2'.

**Comment by bdalevin** [comment]
The phrase "Bin" to mean Downsample is used in Gatan's Digital Micrograph, and in ImageJ, so people should be familiar with this terminology.

**Comment by Hovden** [comment]
Yeah. It's a tough call. Downsample is more widely used and I prefer it slightly. However Bin has the advantage that it tells the user that the values are being averaged (binned) and not sampled by every other pixel (tossing out information; something people actually do).

**Comment by Hovden** [comment]
We can revisit "downsample" v. "bin" in a future pull request. This looks good.

**Pull request merged**
