### PR TITLE
Add progress bar to more tomography reconstructions

### PR DESCRIPTION
**Pull request by yijiang1**
I want to add progress bar to more reconstruction transforms. 
This PR currently adds progress bar to "Direct Fourier Method" but it doesn't work properly and I don't know how to fix it...

Here is the problem:
1. Load a dataset, mark it as tilt series.
2. Run "Direct Fourier Method" reconstruction. The progress bar does not update during reconstruction. It looks like this: 
screen shot 2016-11-02 at 2 19 36 pm

3. After reconstruction finishes, double-click "Reconstruct (Direct Fourier)" in the pipeline.
4. Make some modification to the code (for example, add an empty line), then click "OK".
5. Now reconstruction is re-run and the progress bar seems working:
screen shot 2016-11-02 at 2 19 44 pm

### CODE REVIEW

**Comment by cjh1** [comment]
@yijiang1 I have fixes for this if you give me push access to you PR I can push the changes

**Comment by yijiang1** [comment]
> give me push access to your PR

How can I do this?

**Comment by cjh1** [comment]
@yijiang1 Looks like I already can :smile: There was a missing signal ( may have got lost in a merge ). Also setting progress.maximum as soon as we get into the transform_scalars(...) methods, otherwise we get a busy progress bar ( at 100% ) ... Let me know if these changes make sense to you.

**Comment by yijiang1** [comment]
> Also setting progress.maximum as soon as we get into the transform_scalars(...) methods, otherwise we get a busy progress bar ( at 100% )

I don't quite understand why we need to do this?

**Comment by cjh1** [comment]
If we don't do that the progress bar will default to a busy indicator until you set a maximum progress, which might be OK, but i thought it looks a little odd. As first you would see the progress bar at 100% and then it would jump back to zero when you the set the maximum progress. Comment out the line and you will see what I mean.

From the Qt doc:

"If minimum and maximum both are set to 0, the bar shows a busy indicator instead of a percentage of steps"

**Comment by yijiang1** [comment]
Later in the script (line 49) I set self.progress.maximum to a non-zero integer. So why do I need to do this at the beginning?

**Comment by cjh1** [comment]
Because executing lines 8 - 49 take a couple of seconds ( the first time ), during this time the progress bar will be displayed as a busy indicator ( at 100% ). I would comment out that line and you see what I mean ...

**Comment by yijiang1** [comment]
Ah I see. Thanks for the explanation!

**Comment by cjh1** [comment]
No problem

**Comment by yijiang1** [comment]
Travis is telling me this error:
screen shot 2016-11-03 at 12 48 39 pm
What is my problem and how should I fix it?

**Comment by cjh1** [comment]
@yijiang1 Basically it because your transform_scalars has good too [complicated](https://en.wikipedia.org/wiki/Cyclomatic_complexity) ( to much branching ). I would refactor it to use some more methods, for example encapsulate each branch of the if statement in method.

**Comment by yijiang1** [comment]
I see. I'll refactor the script.

**Comment by yijiang1** [comment]
I've added progress bar to all python-based reconstruction methods. Ready for review and merge.

**Pull request merged**
