### PR TITLE
Clip

### PR DESCRIPTION
**Pull request by bnmajor**
The current clip module is a work in progress.
- Currently using the `vtkNonOrthoImagePlaneWidget` to create the clipping plane since the class already contains all of the plane functionality needed. However it does do more than is needed as it also creates and manages a slice, which is not needed here.
- Despite having used the slice module as a template and starting point, this current implementation is very laggy and occasionally unresponsive to mouse interaction (the slider works consistently, albeit slowly)
- Presently only one, orthogonal clipping plane can be handled at a time
- The actual clipping plane could probably stand to be more obvious, it currently kind of blends into the outline
- The icon is just the slice icon at the moment

### CODE REVIEW

**Comment by cryos** [comment]
Can you take a look at this @alesgenova and offer some input on getting the clipping to work for the plane.

**Comment by bnmajor** [comment]
The clipping plane now works for one or more orthogonal or non-orthogonal planes. The properties panel currently re-uses the same slider and direction functionality that the slice module uses.
clippingPlanes
The border of the non-orthogonal slices does currently extend outside of the outline and should probably be clipped.
nonOrthoClippingPlane

**Comment by cryos** [comment]
This doesn't seem to work for me on my Linux laptop using an embedded Intel GPU. Maybe we can take a look on Thursday, it can be tough to interact with it in the 3D view too.

**Comment by bnmajor** [comment]
The clipping plane can now be toggled on or off and its direction can be inverted.

invertedPlane

hiddenPlanes

The most recent changes also remove the border from the clipping plane and instead increase the opacity of the plane. This keeps the plane clipped to the dimensions of the outline and keeps the plane visible when it is being moved. If it is preferred the border of the plane could be added back in.

clippedClippingPlane

**Comment by cryos** [comment]
You have a commit with the subject "WIP" that should be edited out, or the description fixed. Just taking a look at this locally now.

**Comment by bnmajor** [comment]
Yes, that commit should not have been there at all actually. I'm going to remove it altogether.

**Pull request merged**
