### PR TITLE
Update move objects icon

### PR DESCRIPTION
**Pull request by mathturtle**
Here is the new move objects button icon that Steve and I came up with.  This PR changes the icon used in the menu bar.

hand_box

@cryos

### CODE REVIEW

**Comment by mathturtle** [comment]
The last part to fix #38.

**Comment by cryos** [comment]
Looks good, although the dimensions are off. Can we get one matching the standard toolbar icon size please (that is still 64x64 as far as I remember - definitely square).

**Comment by mathturtle** [comment]
Ok, new 64x64 icon in updated branch.

**Comment by cryos** [comment]
Much better, and we can see how the builds do...

**Pull request merged**
