### PR TITLE
Otsu thresholding

### PR DESCRIPTION
**Pull request by cquammen**
Provide an Otsu Multiple Thresholding operator to compute several thresholds between voxel intensity classes representing different materials.

### CODE REVIEW

**Comment by cquammen** [comment]
Some results from using the filter.

image

The data was thresholded into three classes automatically by the Otsu filter (orthogonal slice, colored with the Cool to Warm colormap). Note the peaks in the histogram/opacity editor. A contour at the higher threshold is also displayed.

**Comment by cquammen** [comment]
Ready for review.

**Comment by cryos** [comment]
Nice visual, thanks for sharing!

**Comment by yijiang1** [comment]
I'm getting this error message:

Exception encountered while running OtsuMultipleThreshold
'LazyITKModule' object has no attribute 'PyBuffer'

Should I re-install my ITK library?

**Comment by cquammen** [comment]
Does running the Binary Threshold or Connected Components transforms invoke the same exception? If so, your ITK build may not have enabled Numpy support. Please ensure that Module_BridgeNumPy is ON in your ITK build.

**Comment by yijiang1** [comment]
> Does running the Binary Threshold or Connected Components transforms invoke the same exception?

Yeah I get same error. I'll rebuild my ITK then.

**Comment by cquammen** [comment]
@cjh1 Mind reviewing? I'd like to see if you get the same errors @yijiang1 is seeing.

For local testing, do:

* File -> Open `SMALL_PtCu_NanoParticle.tif`
* Data Transforms -> Otsu Multiple Thresholds. Use default settings
* Click on the Label Map child data set, then add an orthographic slice
* You should see

image

**Comment by cjh1** [comment]
@cquammen Sure, on it.

**Comment by cjh1** [comment]
I can confirm that this works for me, I see the following:

tomviz

**Comment by cquammen** [comment]
Great, thanks for testing. Mind looking over the code for review now 😀 ?

**Comment by cjh1** [comment]
Just did all LGTM

**Comment by cquammen** [comment]
Thanks!

**Comment by cjh1** [comment]
You trying to get it in before flake8 hits? :smile:

**Comment by cquammen** [comment]
Didn't occur to me, but I guess I managed to avoid a lot of conflicts by doing so 😁

**Pull request merged**
