### PR TITLE
Add support for registering custom operators

### PR DESCRIPTION
**Pull request by cjh1**
Looks in <user home>/.tomviz/ for operators. Would appreciate testing on Mac.

### CODE REVIEW

**Comment by ercius** [comment]
Looking forward to testing this out when it gets in the nightly!

**Comment by cjh1** [comment]
@cryos Shall I go ahead and merge this so we can get @ercius a nightly? We can iterate if problems show up.

**Comment by cryos** [comment]
Absolutely, I am merging this now.

**Comment by cjh1** [comment]
@ercius This should appear in a build tonight. Let me know if you run into any issues. Just create a .tomviz directory in your home directory and place your python operators there, you can also add a .json describing the parameters etc.

**Pull request merged**
