### PR TITLE
Add brightness and contrast controls to AlignWidget.

### PR DESCRIPTION
**Pull request by tjcorona**

### CODE REVIEW

**Comment by tjcorona** [comment]
@cryos Would you mind taking a look and letting me know what you think? Thanks!

**Comment by cryos** [comment]
That isn't what I thought of when suggesting this feature, but it works quite well. It is odd to change the main window, but overall it felt reasonably intuitive to me. That whole dialog needs a little TLC to make resizing/how it fills work better, but we should do that after this is merged.

**Comment by cryos** [comment]
This has some minor formatting issues, any other reason to hold this as a work in progress @tjcorona?

**Comment by cryos** [comment]
If not please rewrite the commit to remove WIP, it is pushed to the main Tomviz repo as a branch too, it would be good to merge this soon so we can remove the branch (we try to keep branches for features in forks).

**Comment by tjcorona** [comment]
@cryos Sorry about that. I've removed the WIP status.

**Pull request closed without merging**
