### PR TITLE
Redesign property panel for contour visualization

### PR DESCRIPTION
**Pull request by yijiang1**
@Hovden , @ElliotPadgett and I had a discussion this afternoon and we want to tweak some UI to improve user experience. This PR changes the property panel for contour visualization to 
screen shot 2016-10-21 at 4 59 29 pm

### CODE REVIEW

**Comment by cquammen** [comment]
I don't have strong feelings about this, but I'm just a little concerned it isn't immediately clear that you need to check the check box to use the solid color. Did you consider a design like this? It might be ever so slightly clearer what it does.

image

One could even have the color button disabled when the checkbox is unchecked so that it is clear you can edit the color when you turn on solid coloring.

**Comment by yijiang1** [comment]
We did, but I think @Hovden prefer to have checkbox on the left and label on the right.

**Comment by ElliotPadgett** [comment]
Disabling the color button would help with clarifying things though.

**Comment by ElliotPadgett** [comment]
Either design by @yijiang1 or @cquammen above seems fine to me.

**Comment by Hovden** [comment]
Checkbox on the left is consistent with all other checkboxes used in tomviz.

I don't feel strongly. If we go with @cquammen 's proposal (which we original used) we need some whitespace between the check box and the color.

**Comment by cquammen** [comment]
> Checkbox on the left is consistent with all other checkboxes used in tomviz.

That's true, so I withdraw my suggestion for moving it.

**Comment by yijiang1** [comment]
@cquammen do you mind adding the disable feature later?
I don't know the best way to connect the QCheckBox to the pqColorChooserButton. Both of them are created inside the "addToPanel" function instead of the class.

**Comment by cquammen** [comment]
Nope, not at all. Go ahead and merge

**Pull request merged**
