### PR TITLE
Add autosave capabilities

### PR DESCRIPTION
**Pull request by mathturtle**
This is still pretty rough, but you autosave/load works.  It should
probably autosave more often (or maybe less, I was able to create an
autosave that would re-create the crash that it was recovering from...)

### CODE REVIEW

**Comment by mathturtle** [comment]
This is to address #82.  There may still be a few issues to work out though.

**Comment by Hovden** [comment]
Cool! Maybe less on the autosave would better solve the re-create crash problem—say every five or ten minutes?

**Comment by mathturtle** [comment]
Do you think 5 minutes would be often enough?  I like the autosave timer idea and it should be simple enough to implement.  As a user how often do you think it should autosave?

**Comment by Hovden** [comment]
My thought; the simplest away to avoid re-crashing is by extending the window of autosave. If a user loses 5 minutes of work that is not a big deal. I'm worried that a user will work for hours without saving and then tomviz crashes (this has happened to me).

How will we handle the long computations though? If there is no crash after completion it saves?

**Comment by cryos** [comment]
I think a timer would be irritating, and is not something I have seen good examples of elsewhere. We could make it configurable, but five minutes seems reasonable to me.

**Comment by cryos** [comment]
Unless you meant a QTimer, non-graphical, in which case - this is the right way to go.

**Comment by mathturtle** [comment]
QTimer is what I thought of when timers were mentioned.  Long computations, as long as they are done on the event loop thread, should block the timer events so autosave will only run if the operation completes.

**Comment by cryos** [comment]
Precisely, with a 5-10 minute interval being pretty reasonable. We should consider adding a settings dialog at some point, and it would be reasonable to expose the number of minutes between autosaves there.

**Comment by mathturtle** [comment]
Rebased to avoid conflicts.  This branch has the 'save every 5 minutes' timer now.

**Comment by mathturtle** [comment]
ping

**Comment by cryos** [comment]
Looks good - let's merge it.

**Pull request merged**
