### PR TITLE
Automatic axis finding python transform

### PR DESCRIPTION
**Pull request by ElliotPadgett**
Includes python transform code for automatically finding in-plane rotation of tilt series relative to axis.  Merging will probably require some cherry-picking of the relevant parts.

### CODE REVIEW

**Comment by Hovden** [comment]
This code uses:
import matplotlib.pyplot as plt

However, matplot lib use is commented out. Since matplotlib is currently not included in tomviz, we should remove it.

**Comment by ElliotPadgett** [comment]
Sorry, that's some testing code that I forgot to clean out. Thanks for spotting it.  I will fix it.

**Comment by ElliotPadgett** [comment]
I removed the matplotlib code and includes.

**Comment by cryos** [comment]
Pull request #145 cherry picks the two new commits, fixes the author name in the git commit, and supersedes this branch that contains divergent history of a previous branch that we fixed up before merging.

**Pull request closed without merging**
