### PR TITLE
Compute some label object shape attributes

### PR DESCRIPTION
**Pull request by cquammen**
Introduces the use of ITK to compute label object shape attributes and
store them in the field data of the output data set. A label object
consists of all the voxels that have a particular label
value. Typically, these voxels are connected in some way, such as in a
connected component.

The attributes computed are object surface area (perimeter in ITK
parlance), object volume (number of voxels multiplied by the voxel
volume), and surface area to volume ratio.

Added to the Connected Components module.

### CODE REVIEW

**Comment by cquammen** [comment]
To test:

- open one of the smaller data sets
- run the Connected Components data transform
- split Layout #1 by clicking the tool button 
image to the right of the "RenderView1" label.
- in the new view, choose a SpreadSheet View
- change the "Showing" combo box from "None" to "PassThrough1". Change "Attribute" to "Field Data".
- note the columns "SurfaceArea", "SurfaceAreaToVolumeRatio", and "Volume"

I would love for someone to look this early iteration over and suggest improvements.

**Comment by cryos** [comment]
Thanks Cory, I will take a look this morning hopefully, and maybe we can talk in the afternoon at some point.

**Comment by cryos** [comment]
I guess my data set is too large (using SMALL_PtCu_NanoParticle) after selecting PassThrough1.

**Comment by cquammen** [comment]
Hmm, should take on the order of seconds to view in the SpreadSheet for that data set.

I would hold off trying this further until after we chat.

**Comment by cquammen** [comment]
Subsumed by better way to report these results in #567.

**Pull request closed without merging**
