### PR TITLE
Change contour module to use flying edges

### PR DESCRIPTION
**Pull request by mathturtle**
@cryos I got sick of fighting with interaction and picking, so I decided to work on this today.  It was pretty easy to get it working.  (At least I assume it works.  The contour is reasonable and it uses all my cores at 100% for a second or two on the large test dataset which seems to imply tbb is working).

### CODE REVIEW

**Comment by Hovden** [comment]
Very cool. Excited to test on large datasets.

**Comment by cryos** [comment]
That is great, and it looks good to me. It is also easy to turn back off, I am on battery and so can't compile but one question is whether flying edges will work without TBB? Otherwise, we will either want to enable it optionally based upon build parameters, or figure something else out. Don't know flying edges well enough, but an ifdef would be simple to add here to make it dependent on whether we are building with TBB.

**Comment by cryos** [comment]
This looks great, merging now.

**Comment by Hovden** [comment]
Much faster.

**Comment by mathturtle** [comment]
To answer Marcus's question: I think it will work even without TBB
enabled.  That is the goal of the SMPTools stuff.  It will just be slow
without TBB.

**Pull request merged**
