### PR TITLE
ModuleContour: switch histogram to reflect current coloring.

### PR DESCRIPTION
**Pull request by tjcorona**

### CODE REVIEW

**Comment by tjcorona** [comment]
This MR causes the histogram to reflect the color-by data selected by the user during contouring. It does not rescale the color range (and I'm not sure that it should).

@cryos Would you mind reviewing this merge request?

**Comment by cryos** [comment]
The one oddness I just noticed is clicking away to another module does as I would expect (set the original histogram back), but when returning it does not change to the segmented histogram in my test. Still a big improvement, but I think we want to restore the selected histogram on return.

**Comment by tjcorona** [comment]
@cryos Mind taking another look?

**Comment by tjcorona** [comment]
Clang formatted. Thanks @cjh1 !

**Comment by cryos** [comment]
This looks good @tjcorona, and the interaction is as I would expect it to be. Thanks!

**Pull request merged**
