### PR TITLE
Import matplotlib colormaps

### PR DESCRIPTION
**Pull request by mathturtle**
@Hovden This branch adds the colormaps from matplotlib that you mentioned in #288.

@cryos These are CC0 licensed, but I'd like to figure out how to at least mention where we got them.  You can't comment Json files, and ParaView uses Json files to store colormaps.  We also need to figure out an appropriate color for 'Not a Number' values (right now I have is set to white for all of them).  I'm also abusing the python script copy and install mechanisms to get the json file included...

### CODE REVIEW

**Comment by cryos** [comment]
Won't ParaView ignore any keys it doesn't recognize? So you could add a key "source" with a value of a URL, even an "attribution" key. Not familiar with ParaView's JSON parsing, but I would imagine these additional keys will be ignored (and could in future be added as optional keys displayed in the interface).

**Comment by mathturtle** [comment]
Good idea.  I've updated the file to attribute the color maps and mention that they are CC0 licensed...

**Comment by mathturtle** [comment]
I was talking to @utkarshayachit yesterday and he said that we should import these into ParaView as well.  So we can either merge this or wait for ParaView to include them and update ParaView...

**Comment by cryos** [comment]
I think merging this now so people can play with it is fine, we can always remove them once they appear in ParaView.

**Pull request merged**
