### PR TITLE
Qt5 porting

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by cryos** [comment]
@mathturtle @cquammen here is the first pass at Qt 5 porting, let me know if you see anything major missing. This branch will require changes to the superbuild before it can be merged.

**Comment by cryos** [comment]
One issue, that I have seen in other applications, is the progress dialog popping up after a few seconds. I just tried delaying the initialization until it is used which looks better. The dialog never seems to get rendered though, which is not all that useful...

**Comment by mathturtle** [comment]
I fixed the parenting issue on the colormap widget.  At least it appears to be fixed by the commit I just added to your branch.

**Comment by cryos** [comment]
Thanks @mathturtle, that looks better here too.

**Comment by cquammen** [comment]
I am testing against Qt5 (5.5.1) from homebrew on Mac. Everything is great except I get this warning message 12 times right at startup.

`0x7feeac460480 void QWindowPrivate::setTopLevelScreen(QScreen *, bool) ( QScreen(0x7feea9e60200) ): Attempt to set a screen on a child window. (:0, )`

Googling around suggests this is a Qt bug, and I'm looking for a solution.

**Comment by cquammen** [comment]
Note that the warning also occurs in the ParaView build on top of which I am building tomviz.

**Comment by cquammen** [comment]
There is a 5.6 tag in the Qt git repository that I checked out and built on El Capitan. In-source builds do not appear to work (QHelp was nowhere to be found). An out-of-source build does appear to work find. I built ParaView 5.0 and tomviz with it successfully.

The `QWindowPrivate::setTopLevelScreen` warning is gone, but the pixelization issue on Retina displays (#19) remains.

**Comment by cryos** [comment]
Sounds good, we need to get retinal resolution pixmaps so that is expected.

**Comment by cquammen** [comment]
Actually, it is rendered text in Qt widgets that are the most obviously aliased.

**Comment by cryos** [comment]
We probably need to tweak the QApplication, I know there are some initialization parameters that I tweaked for Avogadro 2. We can look at this more next week.

**Comment by cquammen** [comment]
Note for superbuild on Mac: if you *don't* use system Qt and you point to the qt5.git repo, then the build fails with

[ 62%] Performing update step for 'qt'
Current branch 5.6 is up to date.
No stash found.
No stash found.
No stash found.
CMake Error at /Users/cory.quammen/bin/tomviz-superbuild/qt/tmp/qt-gitupdate.cmake:136 (message):
  

  Failed to unstash changes in:
  '/Users/cory.quammen/bin/tomviz-superbuild/qt/src/qt/'.

  You will have to resolve the conflicts manually

There are a number of project files generated by Qt's `configure` script that prevent the git update step from working. These files make the submodules appear to be modified, causing the qt update script to attempt to stash the changes, but the files are not in the repository, so no stashing occurs. When it comes time to unstash the changes, unstashing fails because no stash was created. This causes the update script `qt/tmp/qt-gitupdate.cmake` to fail and exit.

**Comment by mathturtle** [comment]
This is (I think) why we use Qt's source tarballs/zips instead of pointing at their repo.  But I would also add that the superbuilds have never really supported reusing a build tree.  For now I would build your own "system" Qt from Qt's repo and point the superbuild at that.

**Comment by cquammen** [comment]
Yep, trying that out now.

**Comment by cryos** [comment]
Qt doesn't support reusing their build trees well at all, you should just use homebrew's Qt, or download the official tarball, verifying the bug goes away with their tag is of course useful. We won't package from your machine anyway, so don't worry too much about building it there.

**Comment by cryos** [comment]
We are planning on merging this shortly, @mathturtle will get the build bots ready, now that 0.7.2 is tagged we can start merging some of the larger changes.

**Pull request merged**
