### PR TITLE
Recon child datasets

### PR DESCRIPTION
**Pull request by mathturtle**
This is most of #764... I have a commit that fixes the DFT_constraint one too (but not on this branch yet), but it changes the UI to make it look like the others, and the discussion on the issue indicates that we may want to keep it the way it looks now.

@cryos @yijiang1

### CODE REVIEW

**Comment by cryos** [comment]
There are a few minor Python formatting issues reported, I will give this a try after lunch.

**Comment by cryos** [comment]
Just testing this now, I think it will need a rebase, and it has some formatting issues flagged in the travis testing.

**Comment by cryos** [comment]
It looks like we need some more work on the pipeline from the user perspective. I get something like the following, and the panel doesn't seem to know what it is, so nothing is shown. I am also unable to visualize the reconstructed volume, and see

    QObject::connect: Cannot queue arguments of type 'vtkSmartPointer<vtkDataObject>'
    (Make sure 'vtkSmartPointer<vtkDataObject>' is registered using qRegisterMetaType().)

**Comment by yijiang1** [comment]
We also need to make simulated tilt series a child data set.

**Comment by cryos** [comment]
This still doesn't work for me, I am loading the tilt-series, running the C++ reconstruction, and I see the same as I pasted above. I can only work with/visualize the parent data set. Same warning messages, this is on Linux.

**Comment by mathturtle** [comment]
... Different test cases.  In my case I was making the tilt series via the python operator that creates one.  And the Python Operator's constructor registers the qMetaTypes that it needs.  But if you don't run a python operator first then the metatypes aren't registered and it fails.  I'm adding a commit to fix it.

**Pull request merged**
