### PR TITLE
Enable ParaView lights inspector

### PR DESCRIPTION
**Pull request by mathturtle**
See #912.

### CODE REVIEW

**Comment by cjh1** [comment]
Do we need to use a new version of ParaView on CI for these changes?

**Comment by cryos** [comment]
Yes, it will need to be moved forward in the superbuild and the CI unfortunately. It is a shame there isn't a simple way to optionally use it with newer ParaView, it is pretty self-contained and won't be exercised by the CI in any way.

**Comment by cjh1** [comment]
Ok, I can push things forward when the superbuild is updated.

**Comment by cjh1** [comment]
CI build are updated to latest ParaView

**Pull request merged**
