### PR TITLE
Improve tilt series generation

### PR DESCRIPTION
**Pull request by yijiang1**
Made some changes to the function that generates a tilt series form a volume:
1. Change the interpolation order to 1 (linear) when rotating volume. This is faster than the default spline interpolation.
2. Redefine x-axis to be the rotation axis and z-axis to be the projection direction. This is consistent with the reconstruction functions.
3. Pad volume so that the entire image is always in the field of view after rotation. 
4. Fix a bug that the function does not work properly with non-cubic volume.
5. Add more description to the UI.

### CODE REVIEW

**Comment by cryos** [comment]
You can just copy and paste the changed lines, or run clang-format on the files locally. Chris added some details to the code style document in the root of the repository.

**Comment by yijiang1** [comment]
Yeah I didn't realize that a space is required after comma. I'll read about the style document.

**Comment by cryos** [comment]
If you look at the detail of a failure it gives you the correctly formatted code on the lines that start with a +, we decided to use this as a simpler way to maintain a consistent coding style. A command line tool can also apply the style to any new code, but the travis service runs it and shows you the old and new lines to remove the need to install/run the tool locally.

**Comment by yijiang1** [comment]
> run clang-format on the files locally

Is there a way to check if my code follows the style?

**Comment by cjh1** [comment]
You can run the following command ( it will check your latest  commit ):

```
git diff -U0 HEAD^ | clang-format-diff.py -p1
``

It will produce no output if your code is formatted correctly. You can add the -i option to clang-format-diff and it will update the code with the required changes for you. See [here](https://github.com/OpenChemistry/tomviz/blob/master/STYLE.md) for more details.

**Comment by Hovden** [comment]
This good to merge now? If the style is fine, code looks OK to me.

**Comment by yijiang1** [comment]
I'm using Mac OS X. Where should I put the "clang-format-diff.py" script?

**Comment by cjh1** [comment]
@yijiang1 Have you installed clang-format using brew? If so you can put the python script anywhere you like, its expecting clang-format to be in the path.

**Comment by yijiang1** [comment]
@cjh1 I installed clang-format using brew and the clang-format-diff.py script is located here: /usr/local/Cellar/clang-format/2015-09-01/share/clang/clang-format.py

When I run "git diff -U0 HEAD^ | clang-format-diff.py -p1" in my tomviz directory, I get a message saying "-bash: clang-format-diff.py: command not found"

**Comment by cjh1** [comment]
@yijiang1 You will need to provide the full path to clang-format-diff.py and it will have to have executable permissions.

**Comment by yijiang1** [comment]
@cjh1 I see. It works now. Thanks!

**Comment by cjh1** [comment]
@yijiang1 No problem, glad you are up and running. Feel free to push a PR to update [STYLE.md](https://github.com/OpenChemistry/tomviz/blob/master/STYLE.md) with better instructions for the Mac.

**Comment by yijiang1** [comment]
ok to merge this branch?

**Pull request merged**
