### PR TITLE
Hide non orthogonal slice arrow

### PR DESCRIPTION
**Pull request by mathturtle**
This branch adds a checkbox to the Slice module to allow hiding the arrow (and disabling interaction with the widget similar to filters with widgets in ParaView).

@Hovden @utkarshayachit @cryos

### CODE REVIEW

**Comment by Hovden** [comment]
The show arrow checkbox works well for me.

Possibly unrelated, the "use separate colormap for this module" checkbox is not working for orthoslice on my OSX build. Might have to do with the OpenGL Errors discussed in https://github.com/OpenChemistry/tomviz/pull/121#discussion_r35362465

**Comment by mathturtle** [comment]
Good catch @Hovden!  Thanks for testing.  I've pushed a new version that fixes the 'use separate colormap for this module' feature for non-orthogonal slice.

**Comment by Hovden** [comment]
Works. Ready for merge.

**Comment by Hovden** [comment]
Given the immediate demand for this feature, I've merged. Hope this is OK.

**Comment by mathturtle** [comment]
@Hovden wrong button to merge...

**Comment by Hovden** [comment]
My fault. Thanks.

**Pull request merged**
