### PR TITLE
Use white background color palette

### PR DESCRIPTION
**Pull request by cquammen**
ParaView has the concept of color palettes, or selections of colors
for different elements in a typical scene (background, foreground,
text) that go well together. Make the color palette intended for
printing on white paper the default.

Addresses #817

### CODE REVIEW

**Comment by cquammen** [comment]
Note that more than one color palette could be exposed via a combo box, for instance, so folks could switch from a printing color palette to a "presentation" color palette where the background is black.

**Comment by cquammen** [comment]
Screen shot with default settings proposed in this patch:

image

**Comment by cryos** [comment]
I would like to expose the palette we have now as the default, a printing palette such as this, and one with a black background. I would also like to make it simple for our users to set the default, and make sure the choice is saved in the state file.

**Comment by cquammen** [comment]
Ready for another look, @cryos . The color palette tool button has a palette icon. Clicking on it brings up a menu of color palettes including default, black background, and white background. The current palette can be saved as default. Saving and loading to a state file appears to work.

**Pull request merged**
