### PR TITLE
Add an ITK segmentation module

### PR DESCRIPTION
**Pull request by mathturtle**
This adds a module that runs an ITK-python script and contours the
resulting data.  I'm just putting this up as something for people to play with right now.  A sample script that can be used with this module is below.  The contour doesn't default right yet...

```python
def run_itk_segmentation(itk_image, itk_image_type):
    # should return the result image and result image type like this:
    # return outImage, outImageType
    itk_filter = itk.ConfidenceConnectedImageFilter[itk_image_type,itk.Image.SS3].New()
    itk_filter.SetInitialNeighborhoodRadius(3)
    itk_filter.SetMultiplier(3)
    itk_filter.SetNumberOfIterations(25)
    itk_filter.SetReplaceValue(255)
    itk_filter.SetSeed((24,65,37))
    itk_filter.SetInput(itk_image)
    itk_filter.Update()
    return itk_filter.GetOutput(), itk.Image.SS3
```

### CODE REVIEW

**Comment by Hovden** [comment]
Is this ready for testing? We can start playing with ITK.

**Comment by mathturtle** [comment]
It is certainly ready for testing.  I'd like some feedback before I spend too much more time on it.  But it is definitely not in its final form and there are a few things I haven't implemented yet (like saving the script in the state file).  That said, this will make it much easier to start playing with ITK since you won't have to worry about any of the VTK to ITK conversion code.

**Comment by Hovden** [comment]
Ok. I'm sitting down with Yi and Elliot and we're trying to understand the ITK documentation.

ITK installation via macports is failing: "Error: python25 is not supported on Yosemite or later." It appears that ITK is made for python25?

It's really tough to follow the c++ ITK docs, is there Python docs / tutorials. For example SetSeed() takes in a variable "const IndexType & 	seed" which is very cryptic. In your example however, it is simple a vector for the x,y,z coordinates.

Also, is this SimpleITK or ITK?

**Comment by mathturtle** [comment]
Right now it is ITK (SimpleITK may be a possibility later).  It looks like the ITK macports recipe is really old and probably hasn't been updated since python 2.5 was the default of OSX.  It looks like homebrew may have an up-to-date recipe, but I'm not sure.  The easiest thing for you to do may be to grab the version I built for the superbuild [here](http://www.tomviz.org/files/itk-4.8.0-macosx10.8.tar.gz).  You'll have to set the PYTHONPATH and DYLD_LIBRARY_PATH so that python can find it.  I posted directions on this issue #158.

>It's really tough to follow the c++ ITK docs

I agree completely.  They use a lot of templates and typedefs to make the types "simpler".  I modified the code for my example from one of their C++ examples.

**Comment by Hovden** [comment]
Thanks for the discussion today, really cleared up some things. No need for SimpleITK at this point. ITK looks really great, but the python docs are really sparse.

It would be nice to have to python ITK tutorials (we can do this to promote ITK and tomviz) and also update the macport build.

Should we merge this pull request so that we can test ITK on the tomviz build? Or wait till it is further developed?

**Comment by cryos** [comment]
I think we can merge it if you feel it would be useful. I am not sure about the value of putting energy into macports, I had multiple issues and have found brew to be far superior. End users will get a binary with everything included.

**Comment by mathturtle** [comment]
I don't have a problem with merging it, but I'd like to at least get the 'save to state file' part working first.  @cryos should probably code review it first too.

If you just want to test ITK, you should be able to do that from the 'Custom Transform' menu item too (this will give you access to a more diverse set of visualization techniques to look at the resulting data too).

**Comment by mathturtle** [comment]
I've finished the serialization code now @cryos, so if you want to merge this it is fine with me.

**Comment by cryos** [comment]
Looks good to me, merging it.

**Pull request merged**
