### PR TITLE
Color ui reorg

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by cryos** [comment]
Hey @mathturtle can you take a quick look at this when you have a chance, and check I haven't missed anything obvious. I will add some of the other buttons, and need to emit a signal for re-renders when switching color maps. I think I also need to remove the color stuff for the discrete module color maps too.

**Comment by mathturtle** [comment]
The only issues I found you appear to already know about:
- 'Use a separate colormap for this module' still uses the old ParaView UI we are trying to remove in the module properties panel.
- It doesn't re-render when I change the preset.

**Comment by mathturtle** [comment]
Tested on OSX too, didn't see anything.

**Comment by mathturtle** [comment]
You'll probably want to revert e89e3004cfba70b59e6e97cd9fded45e94473f5e while you are at it.  Since we no longer have the QVTKWidget-based class in the properties panel (which that commit attempted to fix) and that commit is the direct cause of the recursive repaint bug (#414).

**Comment by cryos** [comment]
I would still rather delay initialization until the panel is actually shown.

**Comment by cryos** [comment]
I think this is ready, merging and heading out. I will check the builds later.

**Pull request merged**
