### PR TITLE
Add a Segment Particles transform

### PR DESCRIPTION
**Pull request by thewtex**
This segments the particles in the LARGE_PtCu_NanoParticles dataset. The
segmented particles have all pores filled in.

The only parameter of the transform is the minimum particle size. This
is specified as a radius in voxels. Structures smaller than this size is
suppressed. This algorithm enhances spherical structures in the image
and suppress streak artifacts.

Addresses #895

### CODE REVIEW

**Comment by thewtex** [comment]
Expected output:

segmentedparticles

This will require ITK 4.11 without refactoring.

**Comment by thewtex** [comment]
With some improvements:

segmentedparticles2

**Comment by cryos** [comment]
This can be merged now, we just need to rebase it/fix the conflicts.

**Comment by thewtex** [comment]
Rebased.

**Pull request merged**
