### PR TITLE
Added "Delete Slices" function

### PR DESCRIPTION
**Pull request by yijiang1**
For #189 , add "Delete slices" that allows users to delete a range of slices along a given axis.
If dataset is marked as a tilt series, the function also deletes corresponding tilt angles.
UI:
screen shot 2015-09-15 at 2 29 29 pm
The range for "start" and "End" Spinbox updates automatically based on axis.

### CODE REVIEW

**Comment by mathturtle** [comment]
I can confirm that it works... We will want to discuss how the UI is implemented.  Having variables for the UI of all the python data transforms in `AddPythonTransformationReaction.h` is not good design.  I'll need to think about how best to do this.  @cryos do you want to weigh in here?

**Comment by mathturtle** [comment]
I've pushed a branch for how I would reorganize this to [my fork](https://github.com/mathturtle/tomviz/tree/deleteSlices).  Essentially, I created a custom widget class that takes care of selecting a range of slices.  This avoids filling up the reaction with fields and slots that are specific to certain operations and you can reuse this if you need to do 'select a range' again for another transform.

**Comment by yijiang1** [comment]
@mathturtle I like that you grouped everything (first slice, last slice, and axis) into a class. 
I was wondering if it's better to have a class that just includes first slice and last slice? It may be used by other UI such as crop and reconstruction functions.

**Comment by mathturtle** [comment]
Hmmm... I don't really see how that would be more useful.  If we need a version without the axis dropdown I can make that part of the UI optional later.  But for first and last slice to make sense you need an axis, even if it is hard-coded.  I don't see many cases where we would want that.

Crop already has a UI that handles 6 way bounds rather than just first and last slice.  I'm going to be pulling this out into a helper widget class that can be reused for other UIs soon.  @Hovden asked for it in #199.

**Comment by yijiang1** [comment]
For crop: tomviz crashes (on OSX) if the start slice is greater than the end slice of the same axis, so we need to update the minimum value allowed in end slice.

For reconstruction: we might want to ask users to specify a range of slices they want to reconstruct. Since projections are stacked in z-direction by default, we no longer need to specify the axis. I'll be working on the UI for reconstruction once the new menu branch (#200 ) is merged.

**Comment by mathturtle** [comment]
You found a new bug.  Can you open an issue about that crop widget crash?  I'll fix it at the same time that I work on #199 to factor out the 'select box' widget.

Re: for reconstruction: I'll add an option to hide the axis selector.  Since it already defaults to the z-axis, that should work fine for the reconstruction UI.  When I've pushed the new version, I'll make a new pull request for it.

**Comment by mathturtle** [comment]
Closing since the PR #205 supersedes this and is merged.

**Pull request closed without merging**
