### PR TITLE
Silent warning ( extra semicolon )

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@cquammen Thanks for the review, I tend to agree, but we have to keep the compiler happy :smile:

**Comment by cquammen** [comment]
I know, it's such a tyrant! I wonder if clang-format is smart enough to appease this tyrant.

**Comment by cjh1** [comment]
I took a quick look at the doc and couldn't see anything obvious.

**Comment by cryos** [comment]
In this one case I kind of agree, but they are macros, so they are different, and missing all the other places people put extra semicolons makes me sad...

**Pull request merged**
