### PR TITLE
Removed resampling from the contour module

### PR DESCRIPTION
**Pull request by psavery**
Resampling was noticeably slowing down contour operations
(and it was running even without segmentation), so it has been removed.

"Color By" was removed from the GUI Contour panel as it is no longer
needed. Any functions and variables that appeared to be no longer needed
were removed as well.

### CODE REVIEW

**Comment by psavery** [comment]
Here is an image of what the contour panel now looks like with the GUI changes. Let me know if anything should be changed.

contour-panel

**Comment by psavery** [comment]
I tried to remove as many variables and functions that are no longer used as I could (so that the module is cleaner).

Let me know if I may have removed something I shouldn't have (although, as far as I can tell, the GUI functions properly), or if I haven't removed something I should have.

**Comment by psavery** [comment]
I had accidentally pushed my branch to openchemistry, which is why I assume there is an extra AppVeyor test on display here. But I deleted that extra branch. So it should be good now.

**Comment by cryos** [comment]
This addresses performance issues pointed out by #1595 and #1596.

**Pull request merged**
