### PR TITLE
Remove the decoration from the pipeline view

### PR DESCRIPTION
**Pull request by cryos**
This gets rid of the arrows, lines, etc from the pipeline view.

### CODE REVIEW

**Comment by cryos** [comment]
image

**Comment by Hovden** [comment]
Looks good.

**Comment by cryos** [comment]
Great, I will get this merged in - as you can see it just enables a custom stylesheet I had experimented with earlier.

**Comment by Hovden** [comment]
bigmac is behind on tomviz builds. If we can get one soon, we will squeeze the new UI screenshot will into Yi's poster.

**Comment by mathturtle** [comment]
bigmac is behind on everything... so it is unlikely to get to tomviz before sometime tonight.  You may just want to create a local build, it will be much faster than waiting on bigmac.

**Pull request merged**
