### PR TITLE
Enable coloring contours by data from a child dataset

### PR DESCRIPTION
**Pull request by cquammen**
When operators that computed label maps were first added to Tomviz, it was possible to change the scalar coloring of contours to the labeling. The refactoring of child datasets to being added as separate data sources removed this capability. This branch restores it by adding a combo box to the Contour module's property panel to enable selection of a child of the current dataset. The selected child dataset is resampled onto the contour and set as the color array, restoring the ability to color a contour by a label map.

To test (takes a while):

* Load LARGE_PtCu_NanoParticles.tiff
* Run Otsu Multiple Threshold, default parameters
* Add Contour module
* Select Label Map child dataset from Otsu Multiple Threshold
* Run Connected Components
* Select Contour module
* Set the "Color By" combo box to "Label Map"
* Rescale color map data range to [600, 822]

Expected result:

image

### CODE REVIEW

**Comment by cquammen** [comment]
Addresses #793

**Comment by cjh1** [comment]
Tested using the instruction provided and get the same result. One issue I did notice is that when I add the contour module I get a strange unresponsive dialog that hangs around, see screenshot below:

dialog

Are you seeing that too? Not sure its related to these changes.

Code looks good.

**Comment by cquammen** [comment]
@cryos Want to weigh in on the UI choice of a combobox listing the child data sets? I'm open to other suggestions.

**Comment by cryos** [comment]
I was just about to take a look at this branch, building now.

**Comment by cquammen** [comment]
> Are you seeing that too? Not sure its related to these changes.

@cjh1 I was not seeing that. Hmm, could you confirm that window doesn't pop up in master? I'm a little worried it is an errant vtkRenderWindow.

**Comment by cjh1** [comment]
@cquammen Just checked on master and I'm not seeing the window when I add the contour module.

**Comment by cquammen** [comment]
Hrmmm... I'll have a look.

**Comment by cryos** [comment]
This caused my poor 24GB desktop to swap a lot, so I don't know if the box popped up (didn't notice it). I do see (and your screenshot seems to show some of that too) multiple colors per particle which isn't what we got before when choosing to color by the label map:

image

**Comment by cryos** [comment]
It also looks like we are showing the wrong color map for the contour, but can view it when clicking on the connected components. This is something we should probably track in an issue, and not pin on this PR, but I see the same thing in your screenshot.

**Comment by cryos** [comment]
Sorry, distracted by a ParaView/VTK bug. I think if you change the color by attribute in the contour then it needs to select the data set being colored by rather than the source as you want to manipulate the transfer function for the active data set being used for coloring. This may require some bigger changes.

It is odd, if I visualize the volume of the labels then it has the colors, but they lack any of the texture of the data. I think even for the volume I would want to see the original volume with the label map controlling the colors. Maybe it would be useful to go over how Slicer and other tools are doing this, as I see some great visuals that appear to be colored by label maps.

I think this is a good exploration, but would like to refine the interaction and visualization output further before we merge it in.

**Comment by cryos** [comment]
Just pinging on this, we can merge what we have and iterate. I would like to figure out what we can do with labels and visualization as this is an important area once we have segmented data that people often want to show.

**Comment by cquammen** [comment]
I'm okay with merging as is if you wish. I probably won't get back to this for a few days at the earliest.

**Comment by cryos** [comment]
Let's loop back to this in a couple of days, I am fine merging what we have but would like to figure out how we plan to get this into a more generally useful form for our end users.

**Comment by cquammen** [comment]
Yep, I have some ideas how to do this and may be able to get to this sooner.

**Pull request merged**
