### PR TITLE
503 crash when deleting

### LINKED ISSUE #503: Crashes when deleting data from pipeline
Load a dataset.
Press delete key.

(Confirmed on OSX)

### PR DESCRIPTION
**Pull request by cquammen**
This is likely to fix #503.

### CODE REVIEW

**Comment by cquammen** [comment]
@cryos This definitely fixes a crash on my system when no data sources are loaded and the delete key is pressed when the pipeline browser has focus.

**Comment by cryos** [comment]
Sounds good, the guards are definitely an improvement, and I would like to see if this helps with the binary installer. It is dependent on the other branch moving panels around for some reason though.

**Comment by cquammen** [comment]
Oops, lazy branch basing. Thanks for catching. I was looking at your branch when I created this branch. Rebasing...

**Comment by cquammen** [comment]
@cryos Mind double-checking my rebase? Thanks.

**Comment by cryos** [comment]
LGTM, merging now

**Pull request merged**
