### PR TITLE
Prefer the active view if it is a RenderView

### PR DESCRIPTION
**Pull request by cryos**
Do some checking to make sure the active view is a RenderView, if it is
anything else set the active view to the first RenderView available.

### CODE REVIEW

**Comment by cryos** [comment]
This fixed #870

**Comment by cryos** [comment]
@cquammen this addresses some changes you made in 9948fd846e4d609bcacfc4504e6c2dee85dcf95b, and preserves using the active view when possible, would you mind taking a look to see if there are any cases you were thinking of there that I might have missed

**Comment by cquammen** [comment]
Works great. I tested the following scenarios:

Load data into default view ✅ 
Create SpreadSheet view. Make it active. Load data. Modules added to first view ✅ 
Create RenderView. Make it active. Load data. Modules added to active view. ✅ 
Make SpreadSheet view active. Load data. Modules added to first view. ✅ 

One scenario where I get a crash:

Create new view panel, but do not create a RenderView or SpreadSheet view. Load data. Crash. ❌ 

Suggested fix: guard for null `view` at LoadDataReaction.cxx:255 and add Modules to first available render view.

**Comment by cryos** [comment]
You sick :dog2:, I never thought of doing anything that perverse! I will add the guard, great catch - thanks @cquammen!

**Comment by cquammen** [comment]
Woof!

**Comment by cryos** [comment]
I don't get that crash, what are you doing, maybe I am missing a step. Line 252 seems to kick in and create a render view if I am sat at the choices, is that not happening for you when trying this?

**Comment by cryos** [comment]
It's OK, I get what you mean now, have a render view, but then sit in another view but don't decide...

**Comment by cquammen** [comment]
Right.

**Comment by cryos** [comment]
Reproduced, fixed, and good to verify it isn't null in any case. Thanks @cquammen

**Pull request merged**
