### PR TITLE
Hide layout tabs to save some vertical space

### PR DESCRIPTION
**Pull request by cquammen**
Requires this change to be merged in ParaView. 

https://gitlab.kitware.com/paraview/paraview/merge_requests/1458

### CODE REVIEW

**Comment by cquammen** [comment]
Addresses #874.

**Comment by cjh1** [comment]
@cquammen I fix up the CI with a new version of ParaView containing your fix.

**Comment by cquammen** [comment]
Great! Could  you move it one more time? Please see #1016.

**Comment by cjh1** [comment]
@cquammen In progress, will restart failing jobs when its done

**Pull request merged**
