### PR TITLE
Convert more operators

### PR DESCRIPTION
**Pull request by cquammen**
This PR includes:

* conversion of a number of data transforms to use JSON for UI generation
* support for UI generation for multi-element parameter values
* simplified UI widget creation for int and double parameter types
* a special parameter type that adds X, Y, Z column headers for data transforms that had those headers before

### CODE REVIEW

**Comment by cquammen** [comment]
Ready for review, @cjh1 @cryos @mathturtle . Thanks in advance.

**Comment by cjh1** [comment]
I am seeing a couple of warnings:

```
/home/cjh/work/source/tomviz/tomviz/OperatorDialog.cxx: In member function ‘QMap<QString, QVariant> tomviz::OperatorDialog::values() const’:
/home/_/work/source/tomviz/tomviz/OperatorDialog.cxx:95:11: warning: unused variable ‘index’ [-Wunused-variable]
       int index = indexString.toInt();
           ^~~~~
/home/_/work/source/tomviz/tomviz/InterfaceBuilder.cxx: In function ‘T {anonymous}::getAs(const Json::Value&) [with T = int]’:
/home/_/work/source/tomviz/tomviz/InterfaceBuilder.cxx:61:7: warning: variable ‘iValue’ set but not used [-Wunused-but-set-variable]
   int iValue = 0;
       ^~~~~~

```

**Comment by cjh1** [comment]
I have run the changed operator and they all seem to function as expected.

**Comment by cquammen** [comment]
Mind having a look again, @cjh1 ? I rebased on master, so you'll need to force update the branch.

**Pull request merged**
