### PR TITLE
Attempt to remove artifacts in initial render windows

### PR DESCRIPTION
**Pull request by cquammen**
Try rendering all views one second after the MainWindow class is instantiated.

### CODE REVIEW

**Comment by cquammen** [comment]
This is a stab at fixing the artifacts seen at startup as described in #511. Because I don't consistently see the artifacts in my Mac development build, I have not been able to verify that this fixes the problem.

We might try merging this to see if it fixes the superbuild for Mac

**Comment by cquammen** [comment]
Mind reviewing, @mathturtle ?

**Comment by mathturtle** [comment]
I might move it to the showEvent() function (near the bottom of the file).  And possibly use a shorter timeout.  I did see the glitch for a second and then the render went through and it dissappeared.

**Comment by cryos** [comment]
This may alleviate the symptom a little but it is clear that the QVTKWidget has issues and is not repainting as often as it should. This even happens on Linux at times, and a render call may make it a little less apparent. The Mac builds are pretty far behind right now, if we want to put this in then add a comment reminding us to remove it once QVTKWidget/its successor is working better.

**Comment by mathturtle** [comment]
Yes, QVTKWidget has issues with Qt5.  And there really isn't a plan to fix it.  So it will be once tomviz migrates to its successor.

**Comment by cquammen** [comment]
I incorporated all suggestions in this branch.

**Comment by mathturtle** [comment]
@cquammen That is MUCH better.  I can barely notice it now and I know what to look for.

**Pull request merged**
