### PR TITLE
ENH: Add BinaryMinMaxCurvatureFlow

### PR DESCRIPTION
**Pull request by fbudin69500**

### CODE REVIEW

**Comment by fbudin69500** [comment]
@cquammen

**Comment by cryos** [comment]
@cjh1 is there a way to get a travis-ci run, I guess just force push a rebase would be simplest?

**Comment by cjh1** [comment]
@cryos Yes, that would do it

**Comment by cjh1** [comment]
@fbudin69500 I am going to rebase on master and force push to trigger travis.

**Comment by cjh1** [comment]
Looks like there are a few flake8 issue to clean up

**Comment by fbudin69500** [comment]
@cjh1 Do you want me to correct these errors or do you want to take care of it?

**Comment by cjh1** [comment]
@fbudin69500 Happy either way :smile:

**Comment by fbudin69500** [comment]
@cjh1 I'll update the code to clean up the flake8 issues. Hopefully after that everything will be green.

**Comment by cjh1** [comment]
@fbudin69500 Excellent thanks.

**Comment by cjh1** [comment]
LGTM

**Pull request merged**
