### PR TITLE
Replaced deprecrated proxy filters.Probe

### PR DESCRIPTION
**Pull request by cquammen**
Replaced with preferred proxy filters.ResampleWithDataset.

### CODE REVIEW

**Comment by cquammen** [comment]
@mathturtle This should fix the warning you described in https://github.com/OpenChemistry/tomviz-superbuild/issues/128.

**Comment by cquammen** [comment]
@cjh1 Mind reviewing?

**Comment by cjh1** [comment]
Sure

**Comment by cquammen** [comment]
Thanks!

**Pull request merged**
