### PR TITLE
Fix up the way modules are remove from a data source

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
Fixes #1560

**Comment by cryos** [comment]
I was going to let @cquammen take a look, but wanted to say that the commit messages look great!

**Comment by cquammen** [comment]
Taking a look now after getting tomviz built with the required ParaView and VTK versions.

**Comment by cquammen** [comment]
Small hiccup: After deleting a clone, the selected element in the pipeline browser is the original data set. However, the context menu that comes up when right clicking the mouse does not enable the `Clone` option again. I have to click a different pipeline object and then click back on the original data to update the context menu.

**Comment by cquammen** [comment]
In fact, all the transforms in the Data Transforms and Segmentation menus are disabled as well until I click a different pipeline object and click the original data again.

**Comment by cjh1** [comment]
@cquammen Is the behavior the same on master? Just try to work out if my commits broke something?

**Comment by cquammen** [comment]
Okay, sorry. After getting ParaView up to the version tomviz needs I forgot to actually grab your branch :face_with_head_bandage: Menu items are enabled as expected. Sorry about that.

Still no crashes when deleting the data, which was the problem you addressed.

Maybe a minor thing, but when I clone a data set, then delete it, upon closing tomviz I get this message:

```
QAbstractItemModel::endRemoveRows:  Invalid index ( -1 , 0 ) in model tomviz::PipelineModel(0x2bb2850)
```

Probably doesn't need to be fixed in this MR, just wanted to note it here.

**Comment by cjh1** [comment]
@cquammen Thanks for the testing. I will try to clear up that warning.

**Comment by cjh1** [comment]
@cquammen I have cleaned up the warning. PTAL.

**Comment by cquammen** [comment]
The warning is gone. Thanks, this is working nicely now! 👏👏👏

**Pull request merged**
