### PR TITLE
Decrease anisotropic diffusion time step default to 0.0625

### PR DESCRIPTION
**Pull request by thewtex**
This avoids the warnings:

WARNING: In /home/matt/src/ITK2/Modules/Filtering/AnisotropicSmoothing/include/itkAnisotropicDiffusionImageFilter.hxx, line 82
GradientAnisotropicDiffusionImageFilter (0x7fc762d60600): Anisotropic diffusion unstable time step: 0.13
Stable time step for this image must be smaller than 0.0625

A smaller (more conservative) default that works well for 3D images.

### CODE REVIEW

**Comment by cquammen** [comment]
I think there still may some issues when the number passes through the double-spinbox in the UI. We may need to increase the number of digits allowed in that UI widget to fully support this - correct me if I am wrong.

**Comment by thewtex** [comment]
@cquammen Yes, the number is rounded to two digits past the decimal point.

The code that generates the double-spinbox should look at the number of digits in the `default` field of the operator `.json` file?

**Comment by cquammen** [comment]
Actually, you can just add the `precision` attribute to the timestep entry, e.g.,

```
    {
      "name" : "timestep",
      "label" : "Time Step",
      "type" : "double",
      "default" : 0.125,
      "minimum" : 0.0,
      "precision" : 4
    }
```

For this operator, maybe set it to 4.

**Comment by thewtex** [comment]
@cquammen Cool! Adding...

**Pull request merged**
