### PR TITLE
Add downsampled versions of matplotlib colormaps

### PR DESCRIPTION
**Pull request by mathturtle**
@Hovden

### CODE REVIEW

**Comment by cryos** [comment]
:+1: LGTM, will let @Hovden take a look, merge if you are happy with it.

**Comment by Hovden** [comment]
There is a problem with the new colormaps autoloading. @mathturtle is aware and will fix it up before we merge.

**Comment by cryos** [comment]
Sounds good.

**Comment by cryos** [comment]
What is happening with this pull request?

**Comment by mathturtle** [comment]
@Hovden Did you ever get a chance to look at this and see what was wrong with the colormap?

**Comment by mathturtle** [comment]
Nevermind, I figured it out.  There was some strange interpolation effect happening between two of the points.  So I changed the color space for the Viridis colormap and now it looks much better.  @cryos I think this is ready to go now.

**Comment by Hovden** [comment]
The code looks good. Hopefully it obeys the autoload properly in the build version.

**Pull request merged**
