### PR TITLE
Change application-wide default color map to grayscale

### PR DESCRIPTION
**Pull request by mathturtle**
@Hovden @cryos @yijiang1 This changes the default color map as we discussed last week.

### CODE REVIEW

**Comment by yijiang1** [comment]
LGTM.

**Comment by cryos** [comment]
Looks good, we want to make sure users can change the default and save that if it is not currently possible too.

**Comment by mathturtle** [comment]
> we want to make sure users can change the default and save that if it is not currently possible too.

It is not currently possible (which is why I didn't feel bad about hardcoding the new default for now).

**Comment by cryos** [comment]
Great, thanks for confirming.

**Comment by mathturtle** [comment]
So can we close #248?

**Pull request merged**
