### PR TITLE
Added Label Object Principal Axes operator

### PR DESCRIPTION
**Pull request by cquammen**
This operator computes the pricipal axes of an object with a
particular label. The principal axes are of interest in a variety of
image analysis applications, particularly those that need the
principal axis of an elongated object such as a cylinder.

### CODE REVIEW

**Comment by cquammen** [comment]
Here is an example of the principal axis computed for a cylindrical object:

image

**Comment by cquammen** [comment]
Testing in Tomviz is a little unusual, but can be done with the following:

* Load SMALL_PtCu_NanoParticle.tiff
* Data Transforms -> Binary Threshold, default arguments. Select the 'Thresholded Segmentation' child dataset.
* Data Transforms -> Label Object Principal Axes, default arguments.

On your terminal, you should see

```
[[  8.71568008e-01  -1.64863555e-04   4.90274597e-01]
 [  4.88568984e-01   8.36334964e-02  -8.68507793e-01]
 [ -4.08601935e-02   9.96496569e-01   7.29728270e-02]]
[ 69.36332092  70.81135612  64.73049734]
```

The first item is a matrix of principal axes (listed column-wise). The second item is the centroid of the object.

You can visualize the axis by opening the Python console and typing the following:

```
line = PolyLineSource()
line.Points = [156.52012172000002, 119.66825452, 60.64447799, -17.793479879999992, 21.95445772, 68.81651669]
Show(line)
```

Here, I have derived two points on the principal axis for you based on the center and principal axis direction.

If you add a Volume module to the input dataset, you should see something like the following in Tomviz:

image

**Comment by cjh1** [comment]
To illustrate my point if I connect the operator directly to the small dataset I get:

```python
Mean of empty slice.
invalid value encountered in true_divide
Degrees of freedom <= 0 for slice
invalid value encountered in true_divide
Failed to execute the script. (/home/cjh/work/source/tomviz/tomviz/OperatorPython.cxx:348, virtual bool tomviz::OperatorPython::applyTransform(vtkDataObject*))
Traceback (most recent call last):
  File "Label Object Principal Axes", line 43, in transform_scalars
  File "Label Object Principal Axes", line 20, in principal_axes
  File "/usr/local/lib/python2.7/dist-packages/scipy/linalg/decomp.py", line 297, in eigh
    a1 = asarray_chkfinite(a)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 613, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

```

**Comment by cquammen** [comment]
Yes, absolutely agree that we should do filtering/inactivating for the currently selected dataset. As I recall, Marcus and I briefly discussed this favorably at one point. Mind creating an issue to discuss such a feature?

**Comment by cjh1** [comment]
@cquammen Sure, here we go #796

**Comment by cquammen** [comment]
Excellent. Thanks for the review, by the way.

In regards to the error you encountered with the SMALL dataset, this error is occurring because the label 1 doesn't occur in the SMALL dataset. I should add some error handling in that case. I'll push a commit on this branch.

**Comment by cjh1** [comment]
Error message looks good.

**Comment by Hovden** [comment]
This is great! More work along these lines (principle moments) can open doors to correlative tomography.

**Pull request merged**
