### PR TITLE
Add an adaptive parameter to TV Minimization.

### PR DESCRIPTION
**Pull request by jtschwar**
Signed-off-by: Jonathan Schwartz <jtschw@umich.edu>

Please provide an overview of what this pull request does, and reference any
relevant issues that are addressed. Once submitted you are encouraged to seek
review of the code, and to check the continuous integration results.

By submitting this pull request I agree to the terms of the
[Developer Certificate or Origin][dco].

  [dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by jtschwar** [comment]
@cjh1 Could you take a look at the error code for travis-ci?

**Comment by cjh1** [comment]
@jtschwar @psavery Has already fixed these in `master`, if you merge master into your branch or rebase on master they should go away.

**Comment by psavery** [comment]
@cjh1 Looks like the flake8 is failing now because "the function is too complex" (C901). I looked it up, flake8 basically deemed the function to have too much branch logic (if statements, loops, etc.). Should we ignore that rule?

**Comment by cjh1** [comment]
@jtschwar Can you refactor the function in question, break into a couple of appropriate functions?

**Pull request merged**
