### PR TITLE
Add a caching operator to the pipeline

### PR DESCRIPTION
**Pull request by cryos**

### CODE REVIEW

**Comment by cryos** [comment]
This addresses issues discussed in #937 and #979.

**Comment by cryos** [comment]
@cquammen we were talking about naming/UI, and @cjh1 suggested renaming this operator to "Snapshot" which I think is a better reflection of what it is. I am happy to rename it, but would appreciate opinions before I do. This operator takes a deep copy of the data, and flatly refuses to do anything else after creation. It behaves largely as clone does, but sits nested in the operator pipeline.

**Comment by cquammen** [comment]
I like "Snapshot". I'll play with this PR early this afternoon.

**Comment by cjh1** [comment]
LGTM, I will let @cquammen have a play

**Comment by cquammen** [comment]
Crash in `OperatorFactory::operatorType(Operator* op)` when state file is saved because there is no case corresponding to this new `Operator`.

**Comment by cryos** [comment]
Thanks for the thorough review Cory. The state files are very crashy in general for cloned data, and this is the same kind of behavior. It is important for us to add checking when saving state to verify data nodes have files to back them up, let's see what we can do to address that in future PRs as you suggest.

**Pull request merged**
