### PR TITLE
Improve set tilt angle UI

### PR DESCRIPTION
**Pull request by yijiang1**
Added a title to the UI.
Made the UI non-resizeable.

### CODE REVIEW

**Comment by Hovden** [comment]
Good point. I would give it a little extra space just in case there was a change in font size.

**Comment by yijiang1** [comment]
The current size looks like this on my Mac Pro (13'')
screen shot 2016-10-24 at 12 35 23 pm

**Comment by ercius** [comment]
Any chance we can add a third box to set the tilt angle step size (1degree,
1.5 degree, etc)? It could be just a reporting box to let the user know
what the current values will produce.

**Comment by yijiang1** [comment]
> It could be just a reporting box to let the user know what the current values will produce.

Done. The UI now looks like
screen shot 2016-10-25 at 4 11 28 pm

**Comment by cquammen** [comment]
If this is ready to merge, please feel free to do so.

**Comment by yijiang1** [comment]
I'm not entirely happy with current UI design but I'll merge this PR for now.
I'll discuss with people at Cornell about improving user experience and post a new issue in the future.

**Pull request merged**
