### PR TITLE
Intro To Visualization Article

### PR DESCRIPTION
**Pull request by jtschwar**
Hi, 
I updated my previous pull request so the button in the help menu opens the link to the article instead of the actual document.

### CODE REVIEW

**Comment by cryos** [comment]
It still cannot be merged as it has the copyrighted PDF in it, and would add this to our history. I will get back to my hotel later tonight and can edit this branch, but we must remove the PDF entirely. Leave it with me.

**Comment by jtschwar** [comment]
I removed the pdf in this branch and now the button opens a url for the Microscopy today journal.

**Comment by cjh1** [comment]
@jtschwar The problem is the PDF is still in the branch history ( and therefore end up in our repository ). @cryos will rewrite the history to remove it.

**Comment by jtschwar** [comment]
I see. I didn't know that was also an issue. Thank you for the clarification @cjh1. 
I can also push a new branch without the previous history if need be.

**Comment by cjh1** [comment]
@jtschwar I just merged in latest master to fix a AppVeyor issue.

**Comment by cjh1** [comment]
Ok bots are happy, merging ...

**Pull request merged**
