### PR TITLE
Show a welcome dialog that asks to load sample data on startup

### PR DESCRIPTION
**Pull request by mathturtle**
@cryos Taking a stab at #277, based loosely on the ParaView welcome dialog.  The UI could certainly be improved, I just threw something together.  I wasn't sure if this was still something we wanted for 0.9 or not.

### CODE REVIEW

**Comment by cryos** [comment]
I think this needs more work, visually I would like to improve it a little, it doesn't detect that sample data is not there, and silently does nothing if it is not. We should use the tomviz logo from the about dialog too. It does nicely show up on first run, and respect the request not to see it again.

**Comment by mathturtle** [comment]
Here is a new version (screenshot below).  It should now detect that the sample data is not present too.  tomviz_welcome_dialog_v2

**Comment by Hovden** [comment]
Looks good. Minor comments:

How does it behave if the dataset is not there? If it isn't, it shouldn't give you the option to load.

I would like it to say "Would you like to load an example dataset and visualization?"

Upon clicking "Yes" it should load a volume render and bounding box. (Orthoslice is optional, whatever you want).

**Comment by cryos** [comment]
Sounds good, once the wording change is integrated we can merge this.

**Comment by mathturtle** [comment]
The wording change is pushed.  @Hovden right now it throws up a warning dialog if the sample data file is not found.  If it is there then it loads it like you would load any other dataset... but changing it to a volume rendering shouldn't be that hard.  @cryos Do we want the other changes that @Hovden asked for in this branch?

**Comment by Hovden** [comment]
We can add a volume render in a new branch.

**Comment by mathturtle** [comment]
@Hovden Your additional requests didn't take very long and I was looking for something quick... See #551.

**Comment by Hovden** [comment]
Sounds good.

**Pull request merged**
