### PR TITLE
Fixed image size for image export

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by jourdain** [comment]
Need to push new web app before merging...

**Comment by cryos** [comment]
Why does this need the webapp to be merged? We should merge it when ready.

**Comment by jourdain** [comment]
Because It is one less merge request. ;-)
I'm almost there too.. ;-)

**Comment by cryos** [comment]
That is fine, I just couldn't understand from the diff :-) We would like to harmonize the file dialog too, hence my slight push but @mathturtle can base it on this PR tip.

**Comment by jourdain** [comment]
Sounds good to me too. If need be, we can merge it as well. 
Updating the JS  sha, won't be an issue anyway.

**Comment by jourdain** [comment]
Should be ready to merge.  Need to synch-up with @mathturtle  changes...

**Comment by mathturtle** [comment]
I don't think there should be any conflicts...

**Pull request merged**
