### PR TITLE
Update PYBIND11_PYTHON_VERSION for Python 3

### PR DESCRIPTION
**Pull request by cjh1**
Merge only when we pull the trigger ...

### CODE REVIEW

**Comment by cjh1** [comment]
@cryos We will need to merge this for python 3. Can you think of a better way than hard coding it?

**Comment by cryos** [comment]
No, and we let our users modify it at least. Maybe we will need to improve the docs a little. We don't *need* 3.6, I would prefer to pin it to 3.x

**Comment by cjh1** [comment]
@cryos I will try using find_package(PythonInterp ...) to get the version and uses those to pass to pybind11.

**Comment by cjh1** [comment]
@cryos I think this is better.

**Comment by cryos** [comment]
Yeah, I think we can leave this alone for now, stick with 2.7 on the CI, and revisit the simplest solution once we have the release out. I will update the build instructions.

**Pull request closed without merging**
