### PR TITLE
Reconstruction ui

### PR DESCRIPTION
**Pull request by mathturtle**
@yijiang1 I've made the UI you talked about in #369.  It still needs a bit of work, but you can try it out if you want.  (The Simple Back Projection (C++) menu item under the Tomography menu pulls it up).

### CODE REVIEW

**Comment by mathturtle** [comment]
Ok, this is rebased and (mostly) cleaned up now.  I had to change the UI a bit since it is just a progress dialog now.  Essentially progress dialogs don't need a start button, and since canceling an operator halfway could leave the DataSource in a weird state I removed the cancel button for now too.

New summary:  This branch adds progress dialogs for running operators.  By default this is just a dialog with a QProgressBar in it, but it can be overridden if an operator has something else it wants to use to display progress.  It also converts the C++ reconstruction code to an operator that uses this functionality.  I also fixed a few bugs I found along the way (a null guard and a memory leak).

@cryos

**Comment by mathturtle** [comment]
Rebased on master so I don't have to keep rebuilding ParaView when I switch branches.

**Comment by mathturtle** [comment]
Fixed another case of blank dialog that didn't paint by making operators emit a dummy "no progress" event before starting.

**Comment by yijiang1** [comment]
Two dialogs boxes are appearing.
Images can still be rotated...
Clicking "OK" button create additional reconstructions.
 
screen shot 2016-05-04 at 3 27 42 pm

**Comment by mathturtle** [comment]
Hmmm, you're right.  Since there are no options to set on the reconstruction, the first dialog is a bit redundant.  (It is the same dialog as editing the other operators, but there are no options on the reconstruction so that part of it is empty)  I'll make it skip that dialog.  Maybe a warning that the reconstuction can be long running?

**Comment by Hovden** [comment]
A single dialogue would be good.

The simplest option would be to have only a cancel button in that dialogue. The a better option would be to also have a button that allows uses to pause / unpause.

**Comment by mathturtle** [comment]
> The a better option would be to also have a button that allows uses to pause / unpause.

I'm curious why you would want to pause.  If you do anything in tomviz that causes the dataset to change, you have to restart the reconstruction anyway.  Is this so you can do something else on your computer that needs a lot of CPU power?

**Comment by Hovden** [comment]
Yeah, reconstruction eats up the CPU resources. In practice most people will not be doing other things while reconstructing a dataset so the pause functionality is not critical. A cancel button is important since you often realize the reconstruction will turn out poorly once it's started.

**Comment by mathturtle** [comment]
So you want to cancel based on the reconstructed slices that the progress dialog shows?

Canceling mid-operation is a more interesting use case.  We need to decide how to handle it.  Do you want it to remove the reconstruction data transform (i.e. not add it at all) or mark it as incomplete/failed somehow?  What about when the user edits something above it in the list of data transforms and it re-executes.  Is canceling it then different?

**Comment by Hovden** [comment]
Cancel button will abort the reconstruction, discard the reconstructed data. It will be in the same state as before the reconstruction operation was clicked.

**Comment by cryos** [comment]
Agreed, I think this is the way any cancel should work. Restore state, remove the operation that was in progress.

**Comment by mathturtle** [comment]
Ok, I just got the Cancel button working as discussed.  It was more complex than I expected since no one part of the system has the information to listen to the Cancel button on the progress dialog and delete the in progress Operator from its DataSource.  Probably some refactoring could be done here, but I haven't come up with anything that works well yet.  So some of this feels a bit hacky.

And I added a commit to disable the interactions that Yi mentioned.

**Comment by Hovden** [comment]
@yijiang1 Does this look OK to you?

**Comment by yijiang1** [comment]
Overall looks good to me. 
Right now the reconstruction starts automatically. Can we have a start button? In general we should have some descriptions about the algorithm and perhaps some parameters for users to specify.

**Comment by Hovden** [comment]
I'm ok with it starting right away if there are no parameters to set for this one. If we add user-specified parameters we can add a start button.

**Comment by mathturtle** [comment]
> Can we have a start button?

The problem with having a start button is that the dialog is no longer purely a progress dialog.  You didn't like the two dialogs with the OK/Apply buttons to start the operation... I suppose we could combine the progress dialog and the settings dialog for all the operators.  That could get messy, but I think it is possible (I'd really rather not do this though).

**Comment by yijiang1** [comment]
> I suppose we could combine the progress dialog and the settings dialog for all the operators.

I think this is best for user experience. We want users to specify parameters (for more advanced reconstruction methods) and view reconstruction progress in one dialog.

**Comment by Hovden** [comment]
Here, we can merge this as a back-projection reconstruction that runs automatically.

Let's discuss the start / apply / pause etc as another issue. We can talk about the tradeoffs between user experience and implementation at the next meeting.

**Comment by yijiang1** [comment]
Agreed

**Pull request merged**
