### PR TITLE
Segment Pores

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
**Really** happy with how this turned out!

segmentpores
segmentpores2

This requires ITK Git master per `BUILDING.md`

**Comment by thewtex** [comment]
Addresses #896

**Comment by cryos** [comment]
This looks great, we need to hold off on merging it as our next release will use ITK 4.11.

**Comment by cjh1** [comment]
@thewtex Wow, that is beautiful! And I love the name "morphological watersheds"

**Comment by Hovden** [comment]
Looks nice.

**Comment by thewtex** [comment]
Thanks, @cryos !

**Pull request merged**
