### PR TITLE
Read in python scripts from files rather than compiling them in

### PR DESCRIPTION
**Pull request by mathturtle**
This is a start on #170, based on a discussion with @cryos a few weeks ago.  This causes the python scripts for the python transforms and sample data to be installed instead of compiled in.  They are installed in X/share since they are not really scripts (they have to have code substituted in to be useful).  If X/share is the wrong place to put them it shouldn't be hard to change.

### CODE REVIEW

**Comment by mathturtle** [comment]
@cryos

**Comment by cryos** [comment]
LGTM

**Comment by yijiang1** [comment]
I can't run any of my python script now and always get this error message:
raise IOError("Couldn't read script file")

**Comment by mathturtle** [comment]
Which OS?  OSX?

Is this in the binaries or in a local build?  I tested all the superbuilds when I first made the branch to ensure that binaries would work.  Has something broken since then?

**Comment by yijiang1** [comment]
@mathturtle It's in my local build and OSX.

**Comment by mathturtle** [comment]
I figured it out.  Local builds on OSX are different from other OSes...  I'll have a patch up in a minute.

**Comment by mathturtle** [comment]
#245 should handle this.  Try it and feel free to merge if it succeeds.

**Pull request merged**
