### PR TITLE
Use vtkSmartPointer to manage members

### PR DESCRIPTION
**Pull request by cryos**
This simplifies memory management logic for members that are assigned
from the outside.

### CODE REVIEW

**Comment by cryos** [comment]
I think this should solve the issue from #1209 while removing manual memory management, it would be good to go through and check we aren't doing this in other places. I don't have a build with debug leaks to confirm, but am pretty certain it will still be leak free.

**Comment by cryos** [comment]
Thanks @mathturtle, debug mode has compile errors, I will get that fixed up.

**Comment by cryos** [comment]
@mathturtle this compiles in debug mode locally.

**Comment by alvarosan** [comment]
+1 for using smart pointers, I should have done that from the beginning.  I will take another pass on these new classes to make sure they are not managing memory manually.

**Pull request merged**
