### PR TITLE
Make itk transforms cancelable

### PR DESCRIPTION
**Pull request by cquammen**
This topic makes the remaining ITK-based data tranforms report progress and cancelable.

### CODE REVIEW

**Comment by cjh1** [comment]
I ran into one issue, if I try to re-execute after a cancel:

```python
Problem encountered while running BinaryDilate
Traceback (most recent call last):
  File "/home/cjh/work/build/tomviz/lib/site-packages/tomviz/itkutils.py", line 383, in _get_itk_image_type
    image_type = vtk_itk_type_map()[vtk_class_name]
KeyError: 'vtkUnsignedCharArray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Binary Dilate", line 76, in transform_scalars
  File "Binary Dilate", line 35, in transform_scalars
  File "/home/cjh/work/build/tomviz/lib/site-packages/tomviz/itkutils.py", line 278, in convert_vtk_to_itk_image
    image_type = _get_itk_image_type(vtk_image_data)
  File "/home/cjh/work/build/tomviz/lib/site-packages/tomviz/itkutils.py", line 385, in _get_itk_image_type
    raise Exception('No ITK type known for %s' % vtk_class_name)
Exception: No ITK type known for vtkUnsignedCharArray
Failed to execute the script. (:0, )
Segmentation fault (core dumped)

```

**Comment by cjh1** [comment]
The cancelling works like a dream :100:

**Comment by cquammen** [comment]
Thanks for the reviews!

@cjh1 That is a very surprising exception. I could not reproduce it when canceling and re-executing the BinaryDilate transform repeatedly.

**Comment by cjh1** [comment]
@cquammen I specialize in very surprising exceptions!

**Pull request merged**
