### PR TITLE
Contour support solid color

### PR DESCRIPTION
**Pull request by mathturtle**
This is based on #613 right now since I was modifying the UI of modules anyway.

This is for #473, which came from a discussion with @ElliotPadgett while visiting Cornell.  For contours it is more useful to let the user set a solid color for the contour.  Because most data in tomviz only has one data array and the contour is by definition an isosurface on that array, the contour will be a solid color anyway.  Depending on the colormap, the contour can be very difficult to see against the background and it is more helpful to just let the user select the color they want it to be.

@cryos

### CODE REVIEW

**Comment by Hovden** [comment]
Elliot was just asking about this! Thanks.

**Comment by cryos** [comment]
This looks good, it depends on the other pull request that introduces a new crash - at least here for me. It would be good to get that figured out or cherry pick this commit.

**Comment by mathturtle** [comment]
If I cherry-pick it, it conflicts with the other branch... and with the new merge rules I'd have to rebase one of them anyway.  So I just rebased on the fixed version of the other branch.

**Comment by Hovden** [comment]
Shouldn't this feature have a checkbox to enable it or something? Right now only uses a solid color.

Also, it has the "Separate Color Map" checkbox that does nothing.

**Comment by cryos** [comment]
Good points, we should make it a check box to enable the feature, and then the separate color map check box would be useful again.

**Comment by mathturtle** [comment]
> Shouldn't this feature have a checkbox to enable it or something? Right now only uses a solid color.

I wondered about that.  This was my general thought process about it:

>Isocontours are by definition solid color anyway, even if you use a color map.
>
>We don't support multiple contours from the same contour module, so there will be at most one color used from the color map.
>
>So why support the whole color map?  I thought about removing the separate color map for this module, but @cquammen's color by label map stuff was still in there and I wasn't sure about removing that.

I can add it back in easily enough.  @cquammen is your color by label map stuff still used at all with the changes to segmentation?

**Comment by cryos** [comment]
I think the visual correspondence with the histogram can be important, and should be preserved. We do support several contour modules in a single view, and being able to see approximate isovalue from the color map has value.

**Comment by Hovden** [comment]
Also, the wireframe surface color does not change color in this after pull request.

**Comment by mathturtle** [comment]
@Hovden #626 makes this optional.  I only just saw your comment about the wireframe, and I'm looking at it now.

**Comment by mathturtle** [comment]
Added a commit to #626 to fix the wireframe.

**Pull request merged**
