### PR TITLE
Reduce wasted space and scroll bar apperances in OperatorPropertiesPanel

### PR DESCRIPTION
**Pull request by cquammen**
The key changes are to enable word wrapping on the QLabel for the operator description and letting the widget inside the scroll area resize. Also, removed manual newline placement in JSON descriptions because wrapping the description is now taken care of by Qt.

Addresses some of the main issues in #1395.

### CODE REVIEW

**Comment by cryos** [comment]
I think one of the most striking things is how overly large the spinners are, like in shift space for 3 characters would be ample:
image

**Comment by cryos** [comment]
Pad is massively improved, so not sure what is different there:
image

**Comment by cryos** [comment]
All done, but for completeness resample ends up huge here
image

**Comment by cquammen** [comment]
Yeah, I'm not sure why that is happening. I'm currently working on changing the horizontal size policy of the spin boxes to see if I can shrink them.

**Comment by cquammen** [comment]
No luck so far changing the sizes of the spin boxes. I'll go ahead and merge.

**Pull request merged**
