### PR TITLE
Toolbar reorganization

### LINKED ISSUE #376: Minor UI Menu reorganization
The "visualization" icons should be moved to the left of the top menu. They are used the most and have a stronger relation to the visualization modules panel.
screen shot 2016-04-21 at 4 16 38 pm

### PR DESCRIPTION
**Pull request by mathturtle**
Fixes #376.  @Hovden you may have to clear your settings before this will display right.  (Run tomviz with `-dr` to disable using the saved Qt settings and see what it will look like without your local settings).

### CODE REVIEW

**Comment by yijiang1** [comment]
> Run tomviz with -dr

@mathturtle Could you be more specific about this? I usually run my tomviz by typing "open tomviz.app" in terminal. Where should I insert "-dr"?

**Comment by mathturtle** [comment]
OSX: `tomviz.app` is really a folder.  Apple hides this from you unless you care about looking inside it.  You can directly run the tomviz executable from the command line by running `tomviz.app/Contents/MacOS/tomviz`.  You can pass the `-dr` as an argument to this.  (Giving the direct path to the executable is also useful if you need to debug tomviz with a debugger).

You could also delete your settings file.  Mine is at: `/Users/shawn/.config/Kitware/tomviz0.8.0.ini`.

**Comment by yijiang1** [comment]
> You could also delete your settings file.

This works.

@Hovden The UI looks like this now:
Without dataset
screen shot 2016-06-05 at 11 18 09 am
screen shot 2016-06-05 at 11 18 42 am

With dataset loaded

**Comment by Hovden** [comment]
great. thanks for testing.

**Pull request merged**
