### PR TITLE
Add table documenting clang-format-diff locations

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@cryos PTAL

**Comment by cjh1** [comment]
@cquammen Could you look up the location on your Mac?

**Comment by cquammen** [comment]
It is not installed with any development tools on the Mac, including the command line tools. I used homebrew to install it. On my system, it is located under `/usr/local/bin/clang-format`. It seems homebrew does not have a `clang-format-diff` available.

**Comment by cjh1** [comment]
Thanks, we add download URL as well.

**Comment by cquammen** [comment]
LGTM

**Comment by cryos** [comment]
LGTM

**Comment by cquammen** [comment]
Any idea what's up with the in-progress Travis CI build?

**Comment by cjh1** [comment]
@cquammen clang-format is now being run by travis. Branches can only be merge when Travis is happy. Not sure why this branch got stuck in the "in-progress" state, but looks like it all good now.

**Pull request merged**
