### PR TITLE
Clone no longer assumes a datasource with a filename property

### PR DESCRIPTION
**Pull request by mathturtle**
@yijiang1 This should address #209.

### CODE REVIEW

**Comment by yijiang1** [comment]
I'm still having the same problem.

**Comment by mathturtle** [comment]
Huh.  This addressed the problem I was seeing.  Let me try it on OSX.

**Comment by mathturtle** [comment]
@yijiang1 Can you tell me exactly what you are doing to get this crash.  I couldn't figure out how to reproduce it on OSX when I built this branch.

**Comment by Hovden** [comment]
On this branch, Clone still crashes tomviz when doing steps in #209 (OSX).

@yijiang1 and I are also getting an OpenGL error and others which may or may not be related:

ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkOpenGLRenderer.cxx, line 443
vtkOpenGLRenderer (0x7feb0c607c60): failed after Clear 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkTextureObject.cxx, line 555
vtkTextureObject (0x7feb0c638e70): failed at glBindTexture(0) 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkTextureObject.cxx, line 555
vtkTextureObject (0x7feb0c638e70): failed at glBindTexture(0) 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/ContextOpenGL2/vtkOpenGLContextDevice2D.cxx, line 636
vtkOpenGLContextDevice2D (0x7feb0c62c200): failed after DrawPoly 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkTextureObject.cxx, line 555
vtkTextureObject (0x7feb0c638e70): failed at glBindTexture(0) 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/ContextOpenGL2/vtkOpenGLContextDevice2D.cxx, line 636
vtkOpenGLContextDevice2D (0x7feb0c62c200): failed after DrawPoly 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkTextureObject.cxx, line 555
vtkTextureObject (0x7feb0c638e70): failed at glBindTexture(0) 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/ContextOpenGL2/vtkOpenGLContextDevice2D.cxx, line 636
vtkOpenGLContextDevice2D (0x7feb0c62c200): failed after DrawPoly 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkTextureObject.cxx, line 555
vtkTextureObject (0x7feb0c638e70): failed at glBindTexture(0) 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/ContextOpenGL2/vtkOpenGLContextDevice2D.cxx, line 636
vtkOpenGLContextDevice2D (0x7feb0c62c200): failed after DrawPoly 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/OpenGL2/vtkTextureObject.cxx, line 555
vtkTextureObject (0x7feb0c638e70): failed at glBindTexture(0) 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
ERROR: In /Users/hovden/Research/Software/TomViz_working/ParaView/VTK/Rendering/ContextOpenGL2/vtkOpenGLContextDevice2D.cxx, line 636
vtkOpenGLContextDevice2D (0x7feb0c62c200): failed after DrawPoly 1 OpenGL errors detected
  0 : (1286) Invalid framebuffer operation
.
.
.

**Comment by mathturtle** [comment]
I think the OpenGL errors are from a recent ParaView change.  I'm going to email the OpenGL2 backend folks about them.  As far as I can tell, you can ignore them.

**Comment by mathturtle** [comment]
I don't know what I'm doing differently, but I cannot reproduce the crash with this branch.  Is your ParaView build up to date?  I'm not really sure why it would matter but that might be the difference.

**Comment by yijiang1** [comment]
@mathturtle I just built my ParaView today. It seems that the program works fine (on this branch) if you use the "Zero Dataset" in sample data. However, it still crashes with real datasets loaded by "File->Open".

**Comment by mathturtle** [comment]
Hmmm.  I fixed the problem where it didn't have a filename.  This must be
something else.  What is the filename of your data file?  Are there any
non-ascii characters in it?

**Comment by yijiang1** [comment]
My file name is simply "recon.tiff".
screen shot 2015-09-24 at 10 16 44 am

**Comment by mathturtle** [comment]
Can you send me a backtrace of where it crashes?  I can't get this to happen on our mac.

**Comment by mathturtle** [comment]
I think I may have found it... try this version.

**Comment by yijiang1** [comment]
Yep. My program no longer crashes. :thumbsup:

**Comment by Hovden** [comment]
This fixes the problem on my machine too. (OSX)

**Pull request merged**
