### PR TITLE
Add set colormap button to manual align widget

### PR DESCRIPTION
**Pull request by mathturtle**
Borrowed code from the HistogramWidget, maybe refactor to avoid duplication?  For #482.

@Hovden Please test.

### CODE REVIEW

**Comment by Hovden** [comment]
Not updating colormap when clicked. Otherwise, would be functional without crashes.

**Comment by Hovden** [comment]
Works! Solves #482

**Comment by Hovden** [comment]
@cryos Merge?

**Comment by cryos** [comment]
Sure, looks good to me.

**Pull request merged**
